# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-02-22 19:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MK_apps', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Operacja',
            new_name='Operation',
        ),
    ]
