# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-02-23 18:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MK_apps', '0002_auto_20200222_1924'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('operation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MK_apps.Operation')),
            ],
            options={
                'verbose_name_plural': 'tools',
            },
        ),
    ]
