# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-02-23 19:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MK_apps', '0003_tool'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tool',
            name='operation',
        ),
        migrations.AddField(
            model_name='tool',
            name='operation',
            field=models.ManyToManyField(to='MK_apps.Operation'),
        ),
    ]
