# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-02-23 19:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MK_apps', '0004_auto_20200223_1909'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperationDescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('operation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MK_apps.Operation')),
            ],
            options={
                'verbose_name_plural': 'operationDescriptions',
            },
        ),
        migrations.RemoveField(
            model_name='tool',
            name='operation',
        ),
        migrations.AddField(
            model_name='tool',
            name='operationDescription',
            field=models.ManyToManyField(to='MK_apps.OperationDescription'),
        ),
    ]
