# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-02-28 20:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MK_apps', '0005_auto_20200223_1929'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='operationdescription',
            options={'verbose_name_plural': 'entry'},
        ),
    ]
